name: "test"

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
    branches:
      - "main"
  workflow_dispatch:

jobs:
  puppetfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Code Check
        run: |
          ruby scripts/codecheck.rb Puppetfile
          scripts/no_config_version.sh

      - name: Fail Code Check Test
        continue-on-error: true
        run: ruby scripts/codecheck.rb tests/Puppetfile
